# Generated by Django 4.2.2 on 2023-09-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_stockhistory_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='phase',
            field=models.CharField(choices=[('SMT', 'SMT'), ('THT', 'THT'), ('tunning', 'tunning'), ('monitor assembly', 'monitor assembly'), ('communication config', 'communication config'), ('analysis', 'analysis'), ('correction', 'correction')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
