# Generated by Django 4.2.2 on 2023-09-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_production_phase_alter_stockhistory_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='phase',
            field=models.CharField(choices=[('SMT', 'SMT'), ('THT', 'THT'), ('tunning', 'tunning'), ('monitor assembly', 'monitor assembly'), ('communication config', 'communication config'), ('analysis', 'analysis'), ('correction', 'correction')], null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='item_name',
            field=models.CharField(null=True),
        ),
    ]
